blank_issues_enabled: false
contact_links:
  - name: Questions & discussions / 使用交流
    url: https://github.com/sh-u-x-in/ros2-dev-extension/discussions
    about: Usage questions, ideas and show-and-tell / 使用问题、想法分享与成果展示
