/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 遍历配置(与 TS 版 WalkOptions 对齐) */
export interface WalkOptionsJs {
  /** 分支时长限制(毫秒):单目录处理上限,超时截断该分支 */
  branchTimeoutMs: number
  /** 总超时时长(毫秒):整个搜索上限,超时整体结束 */
  totalTimeoutMs: number
  /** 最大递归深度 */
  maxDepth: number
  /** 按目录名提前排除 */
  excludedDirNames?: Array<string>
  /** 是否跟随符号链接目录 */
  followSymlinks: boolean
}
/** 遍历结果(与 TS 版 WalkResult 对齐) */
export interface WalkResultJs {
  matches: Array<string>
  timedOut: boolean
  elapsedMs: number
  visitedDirs: number
  loopSkipped: number
}
/**
 * 节点级动态队列并行遍历(worker 数 = CPU 核数)。
 * pattern_type: "exact"(精确文件名) | "regex"(正则);pattern: 对应模式内容。
 */
export declare function walkWithTimeout(root: string, patternType: string, pattern: string, opts: WalkOptionsJs): WalkResultJs
